### ISSUE TITLE
shopware-rector breaks with rector/rector 0.17.1

### ISSUE THREAD

**Issue by m-waechter** [FriendsOfShopware/shopware-rector#18]
### Actual behaviour

https://github.com/FriendsOfShopware/shopware-rector/blob/4fb9afd2092edc55e2ef9c2c0935157f8b53e9f4/config/v6.5/renaming.php#L59 uses RemoveMethodCallParam which was removed with 0.17.1 (see https://github.com/rectorphp/rector/releases and https://github.com/rectorphp/rector-src/pull/4119)

### Expected behaviour

Quickest solution would be to adjust the README to explicitly require the working rector version `composer req rector/rector:0.17.0 frosh/shopware-rector --dev`

### Steps to Reproduce?

Follow the README

**Comment by shyim** [comment]
They restored it again:
https://github.com/rectorphp/rector-src/commit/282ba30ece0c31f03c5a5825c5b9520218c7db8c

**Comment by shyim** [comment]
see https://github.com/FriendsOfShopware/shopware-rector/commit/82dd3211f0067712fcc8b0012543c68d903a971a
