### ISSUE TITLE
Incompatible with Rector 0.18.0

### ISSUE THREAD

**Issue by alessandroaussems** [FriendsOfShopware/shopware-rector#22]
### PHP Version

8.1

### Shopware Version

6.5.4.0

### Actual behaviour

Running Rector throws an error

![CleanShot 2023-08-22 at 13 59 08@2x](https://github.com/FriendsOfShopware/shopware-rector/assets/22371019/05c5a10a-8128-4f33-99dc-ce379335ca2c)

### Expected behaviour

Running Rector should work correctly

### Steps to Reproduce?

I think this is related to https://github.com/rectorphp/rector-src/pull/4698 since the import function has been refactored.

<img width="626" alt="CleanShot 2023-08-22 at 14 00 46@2x" src="https://github.com/FriendsOfShopware/shopware-rector/assets/22371019/85eff35f-7c65-4066-a0ea-6d6ad012f587">

**Comment by rmobis** [comment]
We're having the same issue, had to pin `rector/rector` to `^0.17` which I believe is what `frosh/shopware-rector` should use as the dependency target too, given for versions < `1.0` semver states that breaking changes may be introduced on minor version bumps and using `^` instead of `~` properly accounts for that.

**Comment by rmobis** [comment]
I've setup a MRE on this repo: https://github.com/rmobis/shopware-rector-mre

Cloning and running the following commands should reproduce the issue:

```bash
$ composer install
$ vendor/bin/rector process src --config .\rector.php
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. This change is  intended with container switch.
Imported config paths must be explicit.

**Comment by TomasVotruba** [comment]
Looking at shopware configs, there are just 3 files to include, so there is no need for glob loading. 
https://github.com/FriendsOfShopware/shopware-rector/tree/main/config/v6.5

Also, exact paths allows PHPStan to validate if path exists.

Use exact paths instead :+1:
