### ISSUE TITLE
6.5.0 - Checkout

### ISSUE THREAD

**Issue by shyim** [FriendsOfShopware/shopware-rector#8]
### Please describe the feature you would like to see implemented.

```
src/Core/Checkout/Customer/Subscriber/CustomerNewsletterSubscriber.php: * @deprecated tag:v6.5.0 - newsletter field in customer will be remove on version 6.5.0.
src/Core/Checkout/Customer/CustomerDefinition.php:             * @deprecated tag:v6.5.0 - newsletter field will be remove on version 6.5.0.
src/Core/Checkout/Customer/CustomerEntity.php:     * @deprecated tag:v6.5.0 - will be internal from 6.5.0
src/Core/Checkout/Customer/CustomerEntity.php:     * @deprecated tag:v6.5.0 - $newsletter will be removed use the newsletterRecipents instead
src/Core/Checkout/Customer/CustomerEntity.php:     * @deprecated tag:v6.5.0 - will be internal from 6.5.0
src/Core/Checkout/Customer/CustomerEntity.php:     * @deprecated tag:v6.5.0 - will be internal from 6.5.0
src/Core/Checkout/Customer/CustomerEntity.php:     * @deprecated tag:v6.5.0 - getNewsletter will be removed use the newsletterRecipents instead
src/Core/Checkout/Customer/CustomerEntity.php:     * @deprecated tag:v6.5.0 - getNewsletter will be removed use the newsletterRecipents instead
src/Core/Checkout/Cart/Event/CartMergedEvent.php:     * @deprecated tag:v6.5.0 - Parameter $previousCart will be required
src/Core/Checkout/Cart/CartBehavior.php:     * @deprecated tag:v6.5.0 - Return type will change to bool
src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionIndexer.php:     * @deprecated tag:v6.5.0 The parameter $offset will be native typed
src/Core/Checkout/Promotion/Api/PromotionActionController.php: * @deprecated tag:v6.5.0 - Use PromotionCodeService instead
src/Core/Checkout/Promotion/Util/PromotionCodesRemover.php: * @deprecated tag:v6.5.0 - Use EntityRepositoryInterface instead
src/Core/Checkout/Order/Exception/LanguageOfOrderDeleteException.php:     * @deprecated tag:v6.5.0 - $language parameter will be removed
src/Core/Checkout/Promotion/Util/PromotionCodesLoader.php: * @deprecated tag:v6.5.0 - Use PromotionCodeService instead
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     * @deprecated tag:v6.5.0 - Will be removed. Use getPaymentMethodHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     * @deprecated tag:v6.5.0 Will be removed. Use getPaymentMethodHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     * @deprecated tag:v6.5.0 Will be removed. Use getSyncPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     * @deprecated tag:v6.5.0 Will be removed. Use getAsyncPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     * @deprecated tag:v6.5.0 Will be removed. Use getSyncPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     * @deprecated tag:v6.5.0 Will be removed. Use getAsyncPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     * @deprecated tag:v6.5.0 Will be removed. Use getPreparedPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     * @deprecated tag:v6.5.0 Will be removed. Use getRefundPaymentHandler instead.
```

**Comment by manuelselbach** [comment]
### UPDATE

**TODO**

src/Core/Checkout/Customer/Subscriber/CustomerNewsletterSubscriber.php: 		* @deprecated tag:v6.5.0 - newsletter field in customer will be remove on version 6.5.0.

src/Core/Checkout/Customer/CustomerDefinition.php:             					* @deprecated tag:v6.5.0 - newsletter field will be remove on version 6.5.0.

src/Core/Checkout/Customer/CustomerEntity.php:     								* @deprecated tag:v6.5.0 - will be internal from 6.5.0
src/Core/Checkout/Customer/CustomerEntity.php:     								* @deprecated tag:v6.5.0 - $newsletter will be removed use the newsletterRecipents instead
src/Core/Checkout/Customer/CustomerEntity.php:     								* @deprecated tag:v6.5.0 - will be internal from 6.5.0
src/Core/Checkout/Customer/CustomerEntity.php:     								* @deprecated tag:v6.5.0 - will be internal from 6.5.0
src/Core/Checkout/Customer/CustomerEntity.php:     								* @deprecated tag:v6.5.0 - getNewsletter will be removed use the newsletterRecipents instead
src/Core/Checkout/Customer/CustomerEntity.php:     								* @deprecated tag:v6.5.0 - getNewsletter will be removed use the newsletterRecipents instead

src/Core/Checkout/Cart/Event/CartMergedEvent.php:     							* @deprecated tag:v6.5.0 - Parameter $previousCart will be required

src/Core/Checkout/Cart/CartBehavior.php:     									* @deprecated tag:v6.5.0 - Return type will change to bool

src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionIndexer.php:     		* @deprecated tag:v6.5.0 The parameter $offset will be native typed

src/Core/Checkout/Promotion/Api/PromotionActionController.php: 					* @deprecated tag:v6.5.0 - Use PromotionCodeService instead

src/Core/Checkout/Promotion/Util/PromotionCodesRemover.php: 					* @deprecated tag:v6.5.0 - Use EntityRepositoryInterface instead

src/Core/Checkout/Promotion/Util/PromotionCodesLoader.php: 						* @deprecated tag:v6.5.0 - Use PromotionCodeService instead


**Done**

src/Core/Checkout/Order/Exception/LanguageOfOrderDeleteException.php:     		* @deprecated tag:v6.5.0 - $language parameter will be removed
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     	* @deprecated tag:v6.5.0 Will be removed. Use getPreparedPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     	* @deprecated tag:v6.5.0 Will be removed. Use getSyncPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     	* @deprecated tag:v6.5.0 Will be removed. Use getSyncPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     	* @deprecated tag:v6.5.0 Will be removed. Use getAsyncPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     	* @deprecated tag:v6.5.0 Will be removed. Use getAsyncPaymentHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     	* @deprecated tag:v6.5.0 - Will be removed. Use getPaymentMethodHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     	* @deprecated tag:v6.5.0 Will be removed. Use getPaymentMethodHandler instead.
src/Core/Checkout/Payment/Cart/PaymentHandler/PaymentHandlerRegistry.php:     	* @deprecated tag:v6.5.0 Will be removed. Use getRefundPaymentHandler instead.

**Comment by shyim** [comment]
I will close this as the issue is really old and we should recheck
